#!/usr/bin/env bash

# deploy master and client (stateless)
kubectl create -f es-discovery-svc.yaml
kubectl create -f es-svc.yaml
kubectl create -f es-master.yaml
kubectl create -f es-client.yaml

# deploy stateful service + nfs volumes
kubectl create -f stateful/es-volumes.yaml
kubectl create -f stateful/es-data-svc.yaml
kubectl create -f statefule/es-data-stateful.yaml

# optionally deploy cronjob
kubectl create -f es-curator-config.yaml
kubectl create -f es-curator.yaml
