apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: "default"
  annotations:
    volume.beta.kubernetes.io/storage-class: default
  labels:
    type: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/export/share
    server: d-gp2-ranchermgr-3.imovetv.com
